# Default values for elixier-catalog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

kubectl_image:
  repository: bitnami/kubectl
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"


helm_image:
  repository: registry.gitlab.com/abyres/releases/helm
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "development"

schemaregistry_image:
  repository: registry.gitlab.com/abyres/releases/schemaregistry
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "7.3-20230407.105"

opensearch_image:
  repository: registry.gitlab.com/abyres/releases/opensearch
  pullPolicy: IfNotPresent
  tag: "2.4.1-2"
  
kafka_image:
  repository: registry.gitlab.com/abyres/releases/kafka
  pullPolicy: IfNotPresent
  tag: "3.3.1-2"

neo4j_image:
  repository: registry.gitlab.com/abyres/releases/neo4j-community
  pullPolicy: Always
  tag: "development"

pgsql_image:
  repository: registry.gitlab.com/abyres/releases/pgsql-citus
  pullPolicy: IfNotPresent
  tag: "pgsql14-1.0.2-6"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: 
  runAsUser: 1000
  runAsGroup: 1000 
  fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  domain: elixier.lan

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

initContainers:
  resources:  
   limits:
     memory: 64Mi
   requests: 
     cpu: 10m 
     memory: 16Mi


opensearch:
  env: {}
  replicas: 1 
  resources: 
   limits:
     memory: 2048Mi
   requests:
     cpu: 100m
     memory: 256Mi


neo4j:
  enabled: true
  password: secretpassword

kafka:
  enabled: true
  cluster_id: bwx_CqkkQp64WNqQNNC-Qg
  replicas: 1
  resources: 
   limits:
     memory: 4096Mi
   requests:
     cpu: 200m
     memory: 1280Mi

schemaregistry:
  resources: 
   limits:
     memory: 1024Mi
   requests:
     cpu: 100m
     memory: 256Mi



pgsql: 
  root_password: postgres
  pg_version: 14
  pvc_size: 5Gi
  resources:
   limits:
     memory: 2048Mi
   requests:
     cpu: 100m
     memory: 128Mi

datahub:
  db_name: datahub
  db_user: datahub
  db_password: datahub

keycloak:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

containerWaitTimeout: 3600s

