# Default values for elixier-catalog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

kubectl_image:
  repository: bitnami/kubectl
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"


helm_image:
  repository: registry.gitlab.com/abyres/releases/helm
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "development"

schemaregistry_image:
  repository: registry.gitlab.com/abyres/releases/schemaregistry
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "development"

opensearch_image:
  repository: registry.gitlab.com/abyres/releases/opensearch
  pullPolicy: IfNotPresent
  tag: "2.4.1-2"
  
kafka_image:
  repository: registry.gitlab.com/abyres/releases/kafka
  pullPolicy: IfNotPresent
  tag: "3.3.1-2"

neo4j_image:
  repository: registry.gitlab.com/abyres/releases/neo4j-community
  pullPolicy: Always
  tag: "development"

pgsql_image:
  repository: registry.gitlab.com/abyres/releases/pgsql-citus
  pullPolicy: IfNotPresent
  tag: "pgsql14-1.0.2-6"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: 
  runAsUser: 1000
  runAsGroup: 1000 
  fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  domain: elixier.lan

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

opensearch:
  env: {}
  replicas: 1 

neo4j:
  enabled: true
  password: secretpassword

kafka:
  enabled: true
  cluster_id: bwx_CqkkQp64WNqQNNC-Qg
  replicas: 1

pgsql: 
  root_password: postgres
  pg_version: 14
  pvc_size: 5Gi

datahub:
  db_name: datahub
  db_user: datahub
  db_password: datahub

nodeSelector: {}

tolerations: []

affinity: {}

containerWaitTimeout: 3600s

