apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "elixier.fullname" . }}-createbucket
  labels:
    {{- include "elixier.selectorLabels" . | nindent 4 }}
    component: createbucket
spec:
  completions: 1
  template:
    spec:
      serviceAccountName: {{ include "elixier.serviceAccountName" . }}
      initContainers:
        {{- include "elixier.minio-wait" . | nindent 8 }}
      containers:
        - name: createbucket 
          image: "{{ .Values.mc_image.repository }}:{{ .Values.mc_image.tag }}"
          imagePullPolicy: {{ .Values.mc_image.pullPolicy }}
          command: ["mc", "mb", "minio/warehouse"]
          env:
            - name: MC_HOST_minio
              value: 'http://{{ .Values.minio.root_user }}:{{ .Values.minio.root_password }}@{{ include "elixier.fullname" . }}-minio:9000'
      restartPolicy: Never
  backoffLimit: 10
