apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elixier-stream.fullname" . }}-pki-config
  labels:
    {{- include "elixier-stream.labels" . | nindent 4 }}
type: Opaque
stringData:
  keystore_password: {{ .Values.pki.keystore.password }}
  truststore_password: {{ .Values.pki.truststore.password }}
  keystore_type: {{ .Values.pki.keystore.type }}
  truststore_type: {{ .Values.pki.truststore.type }}
  key_password: {{ .Values.pki.key.password }}

