apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elixier-stream.fullname" . }}-pki
  labels:
    {{- include "elixier-stream.labels" . | nindent 4 }}
type: Opaque
data:
  keystore.p12: |
    {{- .Values.pki.keystore.data | nindent 4 }}
  truststore.p12: |
    {{- .Values.pki.truststore.data | nindent 4 }}
