{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- include "elixier.labels" . | nindent 4 }}
    component: superset
  name: {{ include "elixier.fullname" . }}-superset
spec:
  rules:
  - host: superset.{{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "elixier.fullname" . }}-superset
            port:
              number: 80
        path: /
        pathType: Prefix
{{- end }}
