apiVersion: v1
kind: Service
metadata:
  name: {{ include "elixier-catalog.fullname" . }}-db
  labels:
    {{- include "elixier-catalog.labels" . | nindent 4 }}
    component: database
spec:
  clusterIP: None
  selector:
    {{- include "elixier-catalog.selectorLabels" . | nindent 4 }}
    component: database
