apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "elixier-catalog.fullname" . }}-db
  labels:
    {{- include "elixier-catalog.selectorLabels" . | nindent 4 }}
    component: database
spec:
  serviceName: {{ include "elixier-catalog.fullname" . }}-db
  replicas: 1
  selector:
    matchLabels:
      {{- include "elixier-catalog.selectorLabels" . | nindent 6 }}
      component: database
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "elixier-catalog.selectorLabels" . | nindent 8 }}
        component: database
    spec:
      setHostnameAsFQDN: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "elixier-catalog.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.pgsql_image.repository }}:{{ .Values.pgsql_image.tag }}"
          imagePullPolicy: {{ .Values.pgsql_image.pullPolicy }}
          args: ["initdb"]
          resources:
            {{- toYaml .Values.pgsql.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "elixier-catalog.fullname" . }}-db-datadir
              mountPath: {{ include "elixier-catalog.pgsql.volume_path" . }}
          env:
            - name: PGDATA
              value: {{ include "elixier-catalog.pgsql.volume_path" . }}/{{ .Values.pgsql.pg_version }}
      containers:
        - name: db
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.pgsql_image.repository }}:{{ .Values.pgsql_image.tag }}"
          imagePullPolicy: {{ .Values.pgsql_image.pullPolicy }}
          args: ['start']
          env:
            - name: PGDATA
              value: {{ include "elixier-catalog.pgsql.volume_path" . }}/{{ .Values.pgsql.pg_version }}
          ports:
            - name: pgsql
              containerPort: 5432
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            {{- toYaml .Values.pgsql.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "elixier-catalog.fullname" . }}-db-datadir
              mountPath: {{ include "elixier-catalog.pgsql.volume_path" . }}
      terminationGracePeriodSeconds: {{ .Values.pgsql.termination_grace_period | default "120" }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "elixier-catalog.fullname" . }}-db-datadir
      spec:
        {{ if .Values.storageClass -}}
        storageClassName: {{ quote .Values.storageClass }}
        {{- end }}
        accessModes: 
          - {{ .Values.storageAccessMode | default "ReadWriteMany" }}
        resources:
          requests:
            storage: {{ .Values.pgsql.pvc_size | required "pgsql.pvc_size is required" }}

