apiVersion: v1
kind: Service
metadata:
  name: {{ include "elixier-catalog.fullname" . }}-schemaregistry
  labels:
    {{- include "elixier-catalog.labels" . | nindent 4 }}
    component: schemaregistry
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "elixier-catalog.selectorLabels" . | nindent 4 }}
    component: schemaregistry

