# Default values for elixier-security.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

keycloak_image:
  repository: quay.io/keycloak/keycloak
  pullPolicy: IfNotPresent
  tag: "20.0.3"

pgsql_image:
  repository: registry.gitlab.com/abyres/releases/pgsql-citus
  pullPolicy: Always
  tag: "pgsql14-1.0.2-6"

opensearch_image:
  repository: registry.gitlab.com/abyres/releases/opensearch
  pullPolicy: IfNotPresent
  tag: "2.4.1-2"

ranger_image:
  repository: registry.gitlab.com/abyres/releases/ranger
  pullPolicy: IfNotPresent
  tag: "2.3.0-20230226.214"

kubectl_image:
  repository: bitnami/kubectl
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsUser: mapr
  runAsGroup: mapr
  fsGroup: mapr

securityContext: 
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  domain: elixier.lan

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

containerWaitTimeout: 3600s

nodeSelector: {}

tolerations: []

affinity: {}

initContainers:
  resources: 
   limits:
     memory: 64Mi
   requests:
     cpu: 10m
     memory: 16Mi

pgsql:
  root_password: postgres
  pg_version: 14
  pvc_size: 5Gi
  resources: 
   limits:
     memory: 2048Mi
   requests:
     cpu: 100m
     memory: 128Mi

opensearch:
  env: {}
  replicas: 1
  resources: 
   limits:
     memory: 2048Mi
   requests:
     cpu: 100m
     memory: 256Mi

ranger:
  enabled: false
  db_root_user: postgres
  db_root_password: postgres
  db_type: postgres
  admin_password: Password123
  db_password: password
  db_name: ranger
  db_user: rangeradmin
  resources: 
   limits:
     memory: 2048Mi
   requests:
     cpu: 100m
     memory: 1024Mi

keycloak:
  pvc_size: 500Mi
  resources: 
   limits:
     memory: 1024Mi
   requests:
     cpu: 100m
     memory: 512Mi

