{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "elixier-stream.labels" . | nindent 4 }}
    component: nifi
    subcomponent: server
  annotations:
    {{ if .Values.keycloak.enabled }}
    ingress.kubernetes.io/protocol: https
    traefik.ingress.kubernetes.io/service.serversscheme: https
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{ end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

  name: {{ include "elixier-stream.fullname" . }}-nifi
spec:
  rules:
  - host: nifi.{{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "elixier-stream.fullname" . }}-nifi
            port: 
              {{ if .Values.keycloak.enabled }}
              name: https
              {{ else }}
              name: http
              {{ end }}
        path: /
        pathType: Prefix
  tls:
    - secretName: {{ include "elixier-stream.fullname" . }}-nifi
      hosts:
      - nifi.{{ .Values.ingress.domain }}

{{- end }}
