apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elixier-stream.fullname" . }}-nifi-config
  labels:
    {{- include "elixier-stream.labels" . | nindent 4 }}
type: Opaque
stringData:
  state-management.xml: |
    {{- include "elixier-stream.nifi.state-management" . | nindent 4 }}

  authorizers.xml: |
    {{- include "elixier-stream.nifi.authorizers" . | nindent 4 }}
