apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elixier-stream.fullname" . }}-nifi-secrets
  labels:
    {{- include "elixier-stream.labels" . | nindent 4 }}
type: Opaque
stringData:
  sensitive_props_key: {{ .Values.nifi.sensitive_props_key }}
