apiVersion: v1
kind: Service
metadata:
  name: {{ include "elixier-stream.fullname" . }}-nifi
  labels:
    {{- include "elixier-stream.labels" . | nindent 4 }}
    component: nifi
    subcomponent: server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http

    - port: 8443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "elixier-stream.selectorLabels" . | nindent 4 }}
    component: nifi
    subcomponent: server
