apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elixier.fullname" . }}-presto-cfg
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
type: Opaque
stringData:
  coordinator-config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    query.max-memory=50GB
    query.max-memory-per-node=1GB
    discovery-server.enabled=false
    discovery.uri=http://{{ include "elixier.fullname" . }}-presto-resmgr:8080
    resource-manager-enabled=true
  resmgr-config.properties: |
    resource-manager=true
    resource-manager-enabled=true
    coordinator=false
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    thrift.server.port=8081
    query.max-memory=50GB
    query.max-memory-per-node=1GB
    discovery-server.enabled=true
    discovery.uri=http://localhost:8080
  worker-config.properties: |
    coordinator=false
    http-server.http.port=8080
    query.max-memory=50GB
    query.max-memory-per-node=1GB
    discovery.uri=http://{{ include "elixier.fullname" . }}-presto-resmgr:8080
    resource-manager-enabled=true
  jvm.config: |
    -server
    -Xmx16G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -Dcom.amazonaws.sdk.disableCertChecking=true
