{{ if .Values.kafka.enabled -}}
{{- include "require" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elixier-catalog.fullname" . }}-kafka-config
  labels:
    {{- include "elixier-catalog.labels" . | nindent 4 }}
type: Opaque
stringData:
  server.properties: |
    {{- include "kafka-server-properties" . | nindent 4 }}
{{- end }}
