apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elixier-security.fullname" . }}-keycloak
  labels:
    {{- include "elixier-security.labels" . | nindent 4 }}
    component: keycloak
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.web_instances }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "elixier-security.selectorLabels" . | nindent 6 }}
      component: keycloak
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "elixier-security.selectorLabels" . | nindent 8 }}
        component: keycloak
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "elixier-security.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ include "elixier-security.fullname" . }}-datadir
          persistentVolumeClaim:
            claimName: {{ include "elixier-security.fullname" . }}-keycloak-data

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.keycloak_image.repository }}:{{ .Values.keycloak_image.tag }}"
          imagePullPolicy: {{ .Values.keycloak_image.pullPolicy }}
          args: ["start-dev"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /realms/master
              port: http
          readinessProbe:
            httpGet:
              path: /realms/master
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_PROXY
              value: edge
          volumeMounts:
            - name: {{ include "elixier-security.fullname" . }}-datadir
              mountPath: "/opt/keycloak/data"

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

