apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "elixier-security.fullname" . }}-keycloak-data
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass }}
  {{- end }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.storageAccessMode | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ .Values.keycloak.pvc_size | required "pvc_size is required" }}

