{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
    component: opensearch
    subcomponent: master
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "elixier.fullname" . }}-opensearch
spec:
  rules:
  - host: opensearch.{{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "elixier.fullname" . }}-opensearch
            port:
              number: 9200
        path: /
        pathType: Prefix
  tls:
    - secretName: {{ include "elixier.fullname" . }}-opensearch
      hosts:
      - opensearch.{{ .Values.ingress.domain }}
{{- end }}
