apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elixier.fullname" . }}-ranger-config
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
type: Opaque
stringData:
  install.properties: |
    {{- include "ranger-install-properties" . | nindent 4 }}
