apiVersion: v1
kind: Service
metadata:
  name: {{ include "elixier-security.fullname" . }}-opensearch
  labels:
    {{- include "elixier-security.labels" . | nindent 4 }}
    component: opensearch
    subcomponent: search
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: http
      protocol: TCP
      name: http
    - port: 9300
      targetPort: binary
      protocol: TCP
      name: binary
  selector:
    {{- include "elixier-security.selectorLabels" . | nindent 4 }}
    component: opensearch
    subcomponent: master

