apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elixier.fullname" . }}-secrets
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
type: Opaque
stringData:
  minio_root_user: {{ quote .Values.minio.root_user }}
  minio_root_password: {{ quote .Values.minio.root_password }}
  minio_console_url: {{ quote .Values.minio.console_url }}
