{{ if .Values.kafka.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "elixier.fullname" . }}-kafka-s
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
    component: kafka
    subcomponent: server
spec:
  clusterIP: None
  selector:
    {{- include "elixier.selectorLabels" . | nindent 4 }}
    component: kafka
    subcomponent: server
{{ end }}
