{{- include "require" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elixier.fullname" . }}-s3gw
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
    component: s3gw
    subcomponent: gateway
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.web_instances }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "elixier.selectorLabels" . | nindent 6 }}
      component: s3gw
      subcomponent: gateway
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "elixier.selectorLabels" . | nindent 8 }}
        component: s3gw
        subcomponent: gateway
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "elixier.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- include "elixier.s3gw.volumes" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.s3gw_image.repository }}:{{ .Values.s3gw_image.tag }}"
          imagePullPolicy: {{ .Values.core_image.pullPolicy }}
          args: ["--rgw-dns-name", 
                '{{ include "elixier.s3gw.gw_hostname" . }},{{ include "elixier.fullname" . }}-s3gw.{{ .Release.Namespace }}.svc.cluster.local,{{ include "elixier.fullname" . }}-s3gw',
                "--rgw-backend-store",
                "sfs",
                "--debug-rgw", "INFO",
                "--rgw_frontends",
                "beast port=7480"
                ]
          ports:
            - name: http
              containerPort: 7480
              protocol: TCP
            - name: https
              containerPort: 7481
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- include "elixier.s3gw.volume-mounts" . | nindent 12 }}
          env:
            - name: RGW_DEFAULT_USER_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "elixier.fullname" . }}-secrets
                  key: s3a_access_key
            - name: RGW_DEFAULT_USER_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "elixier.fullname" . }}-secrets
                  key: s3a_secret_key
            - name: RGW_DEFAULT_USER_ID
              value: admin


      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

