apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "elixier.fullname" . }}-s3gw-mb
  labels:
    {{- include "elixier.selectorLabels" . | nindent 4 }}
    component: s3gw
    subcomponent: makebuckets
spec:
  completions: 1
  template:
    spec:
      serviceAccountName: {{ include "elixier.serviceAccountName" . }}
      initContainers:
        {{- include "elixier.wait-s3gw" . | nindent 8 }}
      containers:
        - name: createbucket 
          image: "{{ .Values.mc_image.repository }}:{{ .Values.mc_image.tag }}"
          imagePullPolicy: {{ .Values.mc_image.pullPolicy }}
          command: ["mc", "mb", "-p", "s3gw/warehouse", "s3gw/warehouse/tablespace", "s3gw/warehouse/event_log", "s3gw/filesystem"]
          env:
            - name: MC_HOST_s3gw
              value: 'http://{{ .Values.s3a.access_key }}:{{ .Values.s3a.secret_key }}@{{ include "elixier.fullname" . }}-s3gw:7480'
      restartPolicy: Never
  backoffLimit: 10
