apiVersion: v1
kind: Service
metadata:
  name: {{ include "elixier.fullname" . }}-jupyterhub
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
    component: jupyterhub
    subcomponent: hub
spec:
  clusterIP: None
  selector:
    {{- include "elixier.selectorLabels" . | nindent 4 }}
    component: jupyterhub
    subcomponent: hub

