apiVersion: v1
kind: Service
metadata:
  name: {{ include "elixier.fullname" . }}-jupyterhub-ingress
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
    component: jupyterhub
    subcomponent: hub
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "elixier.selectorLabels" . | nindent 4 }}
    component: jupyterhub
    subcomponent: hub

