{{ if .Values.kafka.enabled -}}
{{- include "require" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elixier-catalog.datahub-name" . }}-config
  labels:
    {{- include "elixier-catalog.labels" . | nindent 4 }}
type: Opaque
stringData:
  values.yaml: |
    {{- include "datahub-values" . | nindent 4 }}
{{- end }}
