{{- include "require" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elixier.fullname" . }}-hue
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
    component: hue
    subcomponent: web
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.web_instances }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "elixier.selectorLabels" . | nindent 6 }}
      component: hue
      subcomponent: web
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "elixier.selectorLabels" . | nindent 8 }}
        component: hue
        subcomponent: web
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "elixier.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ include "elixier.fullname" . }}-hue-config
          secret:
            secretName: {{ include "elixier.fullname" . }}-hue-config
      initContainers:
        {{- include "elixier.wait-db" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.hue_image.repository }}:{{ .Values.hue_image.tag }}"
          imagePullPolicy: {{ .Values.hue_image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "elixier.fullname" . }}-hue-config
              mountPath: /usr/share/hue/desktop/conf/
          env:
            {{- include "elixier.env" . | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

