apiVersion: v1
kind: Service
metadata:
  name: {{ include "elixier-catalog.fullname" . }}-neo4j-nodeport
  labels:
    {{- include "elixier-catalog.labels" . | nindent 4 }}
    component: neo4j
spec:
  type: NodePort
  ports:
    - port: 7687
      targetPort: bolt
      protocol: TCP
      name: bolt
      nodePort: {{ .Values.neo4j.node_port | default "31687" }}
  selector:
    {{- include "elixier-catalog.selectorLabels" . | nindent 4 }}
    component: neo4j

