apiVersion: v1
kind: Service
metadata:
  name: {{ include "elixier-catalog.fullname" . }}-neo4j-ingress
  labels:
    {{- include "elixier-catalog.labels" . | nindent 4 }}
    component: neo4j
spec:
  type: ClusterIP
  ports:
    - port: 7474
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "elixier-catalog.selectorLabels" . | nindent 4 }}
    component: neo4j

